baseURL = "https://www.luxurypalmbeachliving.com/"
languageCode = "en-us"
summaryLength = 25
title = "My New Hugo Site"
[[menu.footer]]
name = "Search Florida Homes"
url = "/search-homes"
weight = 2
[[menu.footer]]
name = "Contact the Team"
url = "/contact"
weight = 4
[[menu.footer]]
name = "Instant Home Valuation"
url = "/home-valuation"
weight = 3
[[menu.footer]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "Search Homes"
parent = "Buyers"
url = "/search-homes"
weight = 1
[[menu.main]]
name = "Blog"
parent = "Resources"
url = "/blog"
weight = 2
[[menu.main]]
name = "Home Value Request"
parent = "Sellers"
url = "/home-valuation"
weight = 1
[[menu.main]]
name = "Resources"
weight = 4
[[menu.main]]
name = "Sellers"
weight = 3
[[menu.main]]
name = "Buyers"
weight = 2
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[outputs]
home = ["HTML", "RSS", "JSON"]
[params]
cloudinary_url = "https://res.cloudinary.com/realestate2/image/upload/"
[taxonomies]
category = "categories"
cities = "cities"
featured = "featured"
properties = "properties"
states = "states"
status = "status"
tag = "tags"
